Updated aton sandbox install and release script

diff --git a/atom/bin/atom-release b/atom/bin/atom-release
--- a/atom/bin/atom-release
+++ b/atom/bin/atom-release
@@ -7,21 +7,22 @@
 cd $ATOM_TOP || exit 1
 
 # checkout master for all repos, ensure it's up to date
+git checkout develop && git pull origin || exit 1
+git checkout master && git pull origin || exit 1
+gitStatus=`git status -sb`
+[ $gitStatus != "## master...origin/master" ] && echo "This does not appear to be a clean master branch" && exit 1
 
 # verify / fetch current release
 #    atom-client/package.json
 #    atom marketplace (https://www.atom.io/api/packages/codestream)
 marketRelease=`get-json-property -j https://www.atom.io/api/packages/codestream -p releases.latest`
 [ -z "$marketRelease" ] && echo "Could not get release from atom marketplace. Aborting" && exit 1
-if [ -f $ATOM_SANDBOX/atom-client/package.json ]; then
-	priorClientRelease=`grep '"version"' $ATOM_SANDBOX/atom-client/package.json|cut -f4 -d\"`
-	[ "$priorClientRelease" != "$marketRelease" ] && echo "marketRelease=$marketRelease, priorClientRelease=$priorClientRelease - aborting" && exit 1
-fi
-# Make sure version in atom-codestream is next for release
-thisRelease=`grep '"version"' package.json|cut -f4 -d\"`
+
+thisRelease=`get-json-property -j package.json -p version`
+[ -z "$thisRelease" ] && echo "Could not determine release from package.json"
 
 echo "
-	priorRelease = $marketRelease
+	marketRelease = $marketRelease
 	thisRelease =  $thisRelease
 "
 
@@ -31,13 +32,12 @@ echo -n "Go (y/N)? "; read ans
 echo npm run bundle
 npm run bundle || exit 1
 
-echo npm run pack $marketRelease
-npm run pack $marketRelease || exit 1
+echo npm run pack $marketRelease --commit-and-push
+npm run pack $marketRelease --commit-and-push || exit 1
 
-echo "cd $ATOM_SANDBOX/atom-client && git commit -am \"Releasing CodeStream $thisRelease\" && git push origin master"
-(cd $ATOM_SANDBOX/atom-client && git commit -am "Releasing CodeStream $thisRelease" && git push origin master) || exit 1
-
+# Sanity check....
 if [ -d /Applications/Atom.app ]; then
+	(cd ../../atom-client && apm uninstall codestream && apm link) || exit 1
 	echo apm install --production teamcodestream/atom-client
 	apm install --production teamcodestream/atom-client || exit 1
 	echo "Santity check..."
@@ -45,25 +45,26 @@ if [ -d /Applications/Atom.app ]; then
 	echo -n "Press ENTER to continue" && read
 fi
 
+echo -n "press ENTER to publish..."; read
 echo "apm publish $thisRelease"
 (cd $ATOM_SANDBOX/atom-client && apm publish $thisRelease) || exit 1
 
-echo "git push origin master (atom-codestream)"
+git status
+echo -n "press ENTER to push (why??)..."; read
+echo "git push origin master"
 git push origin master || exit 1
 
+echo -n "press ENTER to tag..."; read
 tag="atom-$thisRelease"
-echo "Applying tag $tag to all repos..."
-for p in atom-codestream codestream-lsp-agent codestream-components
-do
-	(echo "cd $ATOM_SANDBOX/$p && git tag $tag && git push origin $tag" && cd $ATOM_SANDBOX/$p && git tag $tag && git push origin $tag) || exit 1
-done
+echo "Applying tag $tag..."
+git tag $tag && git push origin $tag
 
 echo "Bumping patch version on develop..."
 git checkout develop || exit 1
 dt-sb-version-tool --bump-version patch || exit 1
 nextVersion=`dt-sb-version-tool --report-version`
 [ -z "$nextVersion" -o "$nextVersion" == "$thisRelease" ] && echo "Uh oh!! Was the version updated properly?" && exit 1
-git commit -am "Auto-bump of version to $nextVersion following marketplace release" || exit 1
+git commit -am "Auto-bump of Atom version to $nextVersion following marketplace release" || exit 1
 git push origin develop || exit 1
 
 exit 0
diff --git a/atom/bin/package-for-release b/atom/bin/package-for-release
--- a/atom/bin/package-for-release
+++ b/atom/bin/package-for-release
@@ -2,23 +2,34 @@
 
 #desc# 'package' up a production build
 
-echo "==== copying files into master branch of public repo at ../atom-client ===="
-cd ..
-git clone --depth 1 https://github.com/teamcodestream/atom-client
+[ -z "$ATOM_SANDBOX" ] && echo "Atom sandbox not loaded" && exit 1
+[ -z "$1" ] && echo "missing current release num. Do not call this script directly" && exit 1
+currentMarketRelease=$1
+[ "$2" == "--commit-and-push" ] && commitAndPush=1 || commitAndPush=0
+
+cd $ATOM_SANDBOX || exit 1
+
+[ -d atom-client ] && echo "Removing pre-existing atom client" && /bin/rm -rf atom-client
+
+echo "Shallow clonling atom client and re-populating"
+git clone --branch master --depth 1 https://github.com/teamcodestream/atom-client
+
 cd atom-client
+
 rm -rf *
-cp -rf ../atom-codestream/dist .
-cp -rf ../atom-codestream/styles .
-cp -rf ../atom-codestream/keymaps .
-cp -rf ../atom-codestream/menus .
-cp ../atom-codestream/package.json .
-cp ../atom-codestream/README.md .
-cp ../atom-codestream/CHANGELOG.md .
+cp -rf ../codestream/atom/dist .
+cp -rf ../codestream/atom/styles .
+cp -rf ../codestream/atom/keymaps .
+cp -rf ../codestream/atom/menus .
+cp ../codestream/atom/package.json .
+cp ../codestream/atom/README.md .
+cp ../codestream/atom/CHANGELOG.md .
 
-echo "==== clean up package.json ===="
-../atom-codestream/bin/clean-metadata.js package.json $1
+echo "==== sanitizing package.json and setting package.json version to $1 ===="
+../codestream/atom/bin/clean-metadata.js package.json $1
 
-echo "==== uninstall current package ===="
-apm uninstall codestream
-echo "==== link package for validation ===="
-apm link
+if [ $commitAndPush -eq 1 ]; then
+	echo "Committing and pushing pre-publish updates"
+	git commit -am "Pre-published updates for $thisRelease" || exit 1
+	git push origin master || exit 1
+fi
