fetch current release from atom marketplace

diff --git a/atom/bin/atom-release b/atom/bin/atom-release
--- a/atom/bin/atom-release
+++ b/atom/bin/atom-release
@@ -8,14 +8,18 @@ cd $ATOM_TOP || exit 1
 
 # verify / fetch current release
 #    atom-client/package.json
-#    atom marketplace api
-priorRelease=`grep '"version"' $ATOM_SANDBOX/atom-client/package.json|cut -f4 -d\"`
-
+#    atom marketplace (https://www.atom.io/api/packages/codestream)
+marketRelease=`get-json-property -j https://www.atom.io/api/packages/codestream -p releases.latest`
+[ -z "$marketRelease" ] && echo "Could not get release from atom marketplace. Aborting" && exit 1
+if [ -f $ATOM_SANDBOX/atom-client/package.json ]; then
+	priorClientRelease=`grep '"version"' $ATOM_SANDBOX/atom-client/package.json|cut -f4 -d\"`
+	[ "$priorClientRelease" != "$marketRelease" ] && echo "marketRelease=$marketRelease, priorClientRelease=$priorClientRelease - aborting" && exit 1
+fi
 # Make sure version in atom-codestream is next for release
 thisRelease=`grep '"version"' package.json|cut -f4 -d\"`
 
 echo "
-	priorRelease = $priorRelease
+	priorRelease = $marketRelease
 	thisRelease =  $thisRelease
 "
 
@@ -25,17 +29,19 @@ echo -n "Go (y/N)? "; read ans
 echo npm run bundle
 npm run bundle || exit 1
 
-echo npm run pack $priorRelease
-npm run pack $priorRelease || exit 1
+echo npm run pack $marketRelease
+npm run pack $marketRelease || exit 1
 
 echo "cd $ATOM_SANDBOX/atom-client && git commit -am \"Releasing CodeStream $thisRelease\" && git push origin master"
 (cd $ATOM_SANDBOX/atom-client && git commit -am "Releasing CodeStream $thisRelease" && git push origin master) || exit 1
 
-echo apm install --production teamcodestream/atom-client
-apm install --production teamcodestream/atom-client || exit 1
-
-echo "Santity check..."
-open /Applications/Atom.app
+if [ -d /Applications/Atom.app ]; then
+	echo apm install --production teamcodestream/atom-client
+	apm install --production teamcodestream/atom-client || exit 1
+	echo "Santity check..."
+	open /Applications/Atom.app
+	echo -n "Press ENTER to continue" && read
+fi
 
 echo "apm publish $thisRelease"
 (cd $ATOM_SANDBOX/atom-client && apm publish $thisRelease) || exit 1
@@ -44,6 +50,7 @@ echo "git push origin master (atom-codestream)"
 git push origin master || exit 1
 
 tag="atom-$thisRelease"
+echo "Applying tag $tag to all repos..."
 for p in atom-codestream codestream-lsp-agent codestream-components
 do
 	(
@@ -51,3 +58,14 @@ do
 		cd $ATOM_SANDBOX/$p && git tag $tag && git push origin $tag || exit 1
 	)
 done
+
+echo "
+*** Don't forget to bump the version for atom-codestream on develop ***
+"
+# git checkout develop || exit 1
+# bump version patch in package.js ??????????
+# git commit -am "Auto-bump of version to XXXX following marketplace release"
+# git push origin master || exit 1
+
+exit 0
+
